services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
    volumes:
      - ./backend/:/home/node/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: on-failure:3
    depends_on:
      - kurrentdb

  kurrentdb:
    image: kurrentplatform/kurrentdb:25.0.1-x64-8.0-bookworm-slim
    environment:
      - KURRENTDB_CLUSTER_SIZE=1
      - KURRENTDB_RUN_PROJECTIONS=All
      - KURRENTDB_START_STANDARD_PROJECTIONS=true
      - KURRENTDB_NODE_PORT=2113
      - KURRENTDB_INSECURE=true
      - KURRENTDB_ENABLE_ATOM_PUB_OVER_HTTP=true
    ports:
      - "2113:2113"
    volumes:
      - type: volume
        source: kurrentdb-volume-data
        target: /var/lib/kurrentdb
      - type: volume
        source: kurrentdb-volume-logs
        target: /var/log/kurrentdb

volumes:
  kurrentdb-volume-data:
  kurrentdb-volume-logs: